name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - micromamba
  - jupyter_server
  - jupyterlite-core >=0.3.0,<0.4.0
  - pip:
      - .
      - jupyterlite-xeus >=0.2.0a0

