name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - micromamba
  - myst-nb
  - jupyterlite-sphinx
  #- geopandas==0.14.4
  #- rtree=1.2
  #- ipyleaflet=0.19
  #- folium==0.13.0
  #- xyzservices>=2022.9.0
  #- libpysal~=4.10
  #- rasterio
  - jupyter_server
  - jupyterlite-core >=0.3.0,<0.4.0
  - pip:
      - .
      - jupyterlite-xeus >=0.2.0a0
      - jupyter_bridge==0.3.5

