name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - micromamba
  - myst-nb
  - jupyterlite-sphinx
  - jupyter_server
  - jupyterlite-core >=0.3.0,<0.4.0
  - pip:
        - .
        - jupyter_bridge==0.3.5
        - jupyterlite-xeus>=0.2.0a0


