name: mesa_geo
channels:
  #Packages must me noarch
  #See available packages at https://beta.mamba.pm/channels/conda-forge?tab=packages
  #- https://repo.mamba.pm/conda-forge
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.10
  - xeus-python
  - pip=24.2
  - pip:
      - mesa~=2.3.0
      - folium==0.13.0
      - rtree==1.2
      - xyzservices>=2022.9.0
      - libpysal~=4.10
      - jupyter_bridge==0.3.5
      - rasterio~=1.3.10
      - geopandas==0.14.4
      - myst_nb>1 #required for build
      - ipyleaflet~=0.19.1
      - jupyterlite_sphinx~=0.15.0
      - jupyterlite-xeus>=0.2.0a0



