name: mesa_geo
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
  - conda-forge
  - defaults
dependencies:
  - xeus-python
  - pip=24.2
  - pip:
      - mesa~=2.3.0
      - rtree=1.0
      - xyzservices>=2022.9.0
      - libpysal~=4.10
      - jupyter_bridge==0.3.5
      - rasterio~=1.3.10
      - geopandas==0.14.4
      - myst_nb>1 #required for build
      - ipyleaflet~=0.19.1
      - jupyterlite_sphinx~=0.15.0
      - jupyterlite-xeus>=0.2.0a0



