name: mesa_geo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - pip=23.3.1
  - pip:
      - mesa~=2.3.0
      - xyzservices>=2022.9.0
      - libpysal~=4.10
      - rtree~=1.2
      - rasterio~=1.3.10
      - jupyter_bridge==0.3.5
      - geopandas==0.14.4
      - myst_nb>1 #required for build
      - jupyterlite_sphinx~=0.15.0
      - jupyterlite-xeus>=0.2.0a0


